### ISSUE TITLE
VET failing again

### ISSUE THREAD

**Issue by brennanhughey** [gwpy/vet#22]
VET is consistently crashing at both LHO and LLO with the following error, which Duncan notes may be related to the function actually living gwsumm.channels

```
 File "/home/detchar/.conda/envs/ligo-summary-3.7/lib/python3.7/site-packages/gwvet/tabs.py", line 36, in <module>
    from gwsumm.data import get_channel
ImportError: cannot import name 'get_channel' from 'gwsumm.data' (/home/detchar/.conda/envs/ligo-summary-3.7/lib/python3.7/site-packages/gwsumm/data/__init__.py) 
```

**Comment by alurban** [comment]
@brennanhughey, can you post the exact command-line you're trying to run, so that I can attempt to reproduce it and work on a fix?

**Comment by brennanhughey** [comment]
e.g. 
./run.sh in /home/bhughey/public_html/VET/O3/wind_check at LHO
